export type column = {
  dataIndex?: string;
  title: string;
  editable?: boolean;
  align?: AlignSetting;
  width?: string;
  max?: number;
  min?: number;
  children?: column[];
};

export type conduct = {
  ordinalNumber: number;
  studentId: string;
  studentName: string;
  studentBirthday: string;
  pointAverage: number;
  totalNumOfCredits: number;
  totalNumOfFailCredits: number;
  persentOfFailCredits?: string;
  id: number;
  i_1: number;
  i_2: number;
  i_3: number;
  i_4?: number;
  i_5?: number;
  i_6?: number;
  i?: number;
  iI_1: number;
  iI_2: number;
  iI_3: number;
  iI_4: number;
  iI_5: number;
  iI_6: number;
  iI?: number;
  iiI_1: number;
  iiI_2: number;
  iiI_3: number;
  iiI?: number;
  iV_1: number;
  iV_2: number;
  iV_3: number;
  iV?: number;
  v_1: number;
  v_2: number;
  v?: number;
  total?: number;
  classification?: string;
};
